tap "aws/tap"
tap "bufbuild/buf" # full-only
tap "ktr0731/evans" # full-only
tap "oncletom/cpdf" # full-only
tap "sanemat/font"
tap "supabase/tap"
brew "xz"
brew "zstd"
brew "little-cms2"
brew "jpeg-xl"
brew "aom"
brew "pycparser"
brew "lua"
brew "openssl@3"
brew "clingo"
brew "aspcud"
brew "awscli"
brew "axel" # full-only
brew "bat"
brew "boost"
brew "btop"
brew "glib"
brew "coreutils"
brew "unbound"
brew "gnutls"
brew "emacs" # full-only
brew "cask" # full-only
brew "libyaml"
brew "python@3.13"
brew "cfn-lint" # full-only
brew "ctop"
brew "curl"
brew "deno"
brew "exiftool" # full-only
brew "ffmpeg"
brew "fswatch"
brew "gawk"
brew "gcc"
brew "libavif"
brew "webp"
brew "gd"
brew "gdk-pixbuf"
brew "gh"
brew "harfbuzz"
brew "openjpeg"
brew "leptonica"
brew "tesseract" # full-only
brew "ghostscript" # full-only
brew "git"
brew "git-flow"
brew "git-secrets"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "gobject-introspection"
brew "gpgme"
brew "netpbm"
brew "gts"
brew "librsvg"
brew "graphviz" # full-only
brew "grep"
brew "guile"
brew "hdf5" # full-only
brew "hub" # full-only
brew "libheif"
brew "imagemagick"
brew "jq"
brew "libass"
brew "libdap"
brew "libfido2"
brew "proj"
brew "libgeotiff"
brew "libmatio"
brew "libpq"
brew "libraw"
brew "libspatialite"
brew "make"
brew "mint" # full-only
brew "mkcert"
brew "mp4v2" # full-only
brew "netcdf" # full-only
brew "nghttp2"
brew "open-mpi" # full-only
brew "peco"
brew "poppler" # full-only
brew "qt@5" # full-only
brew "poppler-qt5" # full-only
brew "portaudio"
brew "postgresql@14", restart_service: :changed
brew "pstree"
brew "pygobject3"
brew "qpdf" # full-only
brew "re2"
brew "ripgrep"
brew "scrcpy" # full-only
brew "sfcgal"
brew "tesseract-lang" # full-only
brew "vim"
brew "vips" # full-only
brew "watch"
brew "wget"
brew "wxwidgets"
brew "xcodegen" # full-only
brew "yt-dlp" # full-only
brew "zsh"
brew "bufbuild/buf/buf" # full-only
brew "ktr0731/evans/evans" # full-only
brew "oncletom/cpdf/cpdf" # full-only
brew "supabase/tap/supabase"
cask "adobe-acrobat-reader"
cask "antigravity"
cask "aqua-voice"
cask "aws-vault-binary"
cask "chatgpt"
cask "chrome-remote-desktop-host"
cask "chromedriver"
cask "claude"
cask "clipy"
cask "cursor"
cask "discord"
cask "docker-desktop"
cask "dropbox"
cask "figma@beta"
cask "fork"
cask "gcloud-cli"
cask "gimp"
cask "google-chrome"
cask "hammerspoon" # full-only
cask "iterm2"
cask "karabiner-elements" # full-only
cask "monitorcontrol"
cask "slack"
cask "spotify"
cask "thebrowsercompany-dia"
cask "visual-studio-code"
cask "zoom"
vscode "anthropic.claude-code"
vscode "bierner.markdown-mermaid"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-complete-tag"
vscode "gera2ld.markmap-vscode"
vscode "openai.chatgpt"
vscode "redhat.vscode-yaml"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "simonsiefke.svg-preview"
vscode "tombonnike.vscode-status-bar-format-toggle"
vscode "vscodevim.vim" # full-only
go "github.com/mattn/memo"
npm "@antfu/ni"
npm "@anthropic-ai/claude-code"
npm "@google/gemini-cli"
npm "@openai/codex"
npm "corepack"
npm "eslint"
npm "md-to-pdf"
npm "neonctl"
npm "npm-check-updates"
npm "pnpm"
npm "prettier"
npm "ts-node"
npm "typescript"
npm "typesync"
npm "vercel"
npm "yarn"
