#!/bin/bash

set -eux

DOTFILES=~/dotfiles
DEST=$DOTFILES/pkg/.anyenv

# change anyenv root to DEST
export ANYENV_ROOT=$DEST

NODENV_ROOT=$DEST/envs/nodenv

has () {
  type "$1" > /dev/null 2>&1
}

install-anyenv() {
  # anyenv
  if ! has "${DEST}"/bin/anyenv; then
    rm -rf $DEST
    git clone https://github.com/anyenv/anyenv "${DEST}" && "${DEST}"/bin/anyenv install --init
  fi

  # anyenv-update
  if ! has "${DEST}"/plugins/anyenv-update; then
    [ ! -d "${DEST}"/plugins/anyenv-update ] && git clone https://github.com/znz/anyenv-update.git "${DEST}"/plugins/anyenv-update
  fi

  # nodenv
  if ! has "${NODENV_ROOT}"/bin/nodenv; then
    "${DEST}"/bin/anyenv install nodenv

    # nodenv-default-packages
    [ ! -d "${NODENV_ROOT}"/plugins/nodenv-default-packages ] && git clone -q https://github.com/nodenv/nodenv-default-packages.git "${NODENV_ROOT}"/plugins/nodenv-default-packages
    [ ! -e "${NODENV_ROOT}"/default-packages ] && ln -sf "${DOTFILES}"/misc/default-packages "${NODENV_ROOT}"/.
  fi
}
