#!/bin/bash

run_apt() {
  echo "Installing Packages..."

  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

  sudo apt install software-properties-common -y
  sudo apt update && sudo apt upgrade -y
  [[ $? ]] && echo "$(tput setaf 2)Update Packages complete. ✔︎$(tput sgr0)"

  local list_formulae
  local -a missing_formulae
  local -a desired_formulae=(
    'autoconf'
    'automake'
    'awscli'
    'bind9-dnsutils'
    'bison'
    'build-essential'
    'coreutils'
    'curl'
    'dnsmasq-base'
    'docker'
    'docker-compose'
    'gcc'
    'git'
    'golang'
    'grep'
    'imagemagick'
    'iproute2'
    'iptables'
    'iputils-ping'
    'isc-dhcp-client'
    'jq'
    'libffi-dev'
    'libgdbm-dev'
    'libncurses5-dev'
    'libssl-dev'
    'libreadline6-dev'
    'libyaml-dev'
    'mlocate'
    'netcat-openbsd'
    'procps'
    'python3'
    'vim'
    'wget'
    'zlib1g-dev'
    'zsh'
  )

  local installed=$(apt list --installed >&1 | grep -v deinstall | awk -F/ '{print $1}')

  for index in ${!desired_formulae[*]}
  do
    local formula=`echo ${desired_formulae[$index]} | cut -d' ' -f 1`
    if [[ -z `echo "${installed}" | grep "^${formula}$"` ]]; then
      missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
    else
      echo "Installed ${formula}"
    fi
  done

  if [[ "$missing_formulae" ]]; then
    list_formulae=$( printf "%s " "${missing_formulae[@]}" )

    echo "Installing missing package formulae..."
    sudo apt install -y $list_formulae

    [[ $? ]] && echo "$(tput setaf 2)Installed missing formulae ✔︎$(tput sgr0)"
  fi
}

